"use client";
import Link from "next/link";
import {FormEvent,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import "./city.css";
type Listing={name:string;area:string;tags:string[];rating:string;photo:number};
const listings:Listing[]=[{name:"Brew & Bean Café",area:"Connaught Place",tags:["Food & Drink","Café"],rating:"4.6",photo:4},{name:"The Flower Boutique",area:"Greater Kailash",tags:["Flowers","Gifting"],rating:"4.7",photo:5},{name:"Zenith Dental Care",area:"Rohini",tags:["Health","Dental"],rating:"4.5",photo:1},{name:"Pure Bliss Spa",area:"Dwarka",tags:["Spa","Massage"],rating:"4.6",photo:6},{name:"Urban Nest Interiors",area:"Malviya Nagar",tags:["Home","Interiors"],rating:"4.7",photo:7},{name:"Collab Space",area:"Noida Sector 62",tags:["Office","Coworking"],rating:"4.6",photo:3}];
const featured=[{name:"Luxe Salon Studio",area:"Connaught Place",tags:["Beauty","Salon"],rating:"4.7",photo:0},{name:"Serene Wellness",area:"South Delhi",tags:["Wellness","Yoga"],rating:"4.8",photo:1},{name:"The Ambience Venue",area:"Saket",tags:["Events","Venue"],rating:"4.6",photo:2},{name:"Workhub Offices",area:"Gurgaon",tags:["Office","Coworking"],rating:"4.5",photo:3}];
const areas=["Connaught Place","South Delhi","Rohini","Dwarka","Saket","Gurgaon"],areaCards=[["South Delhi","312"],["Central Delhi","286"],["West Delhi","198"],["North Delhi","174"],["Noida","216"],["Gurgaon","248"]],nearby=[["Jaipur","412"],["Chandigarh","287"],["Dehradun","193"],["Agra","176"],["Lucknow","165"]];
function Icon({name,size=18}:{name:string,size?:number}){const p:Record<string,React.ReactNode>={pin:<><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,search:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,list:<><path d="M9 6h11M9 12h11M9 18h11"/><circle cx="4" cy="6" r="1"/><circle cx="4" cy="12" r="1"/><circle cx="4" cy="18" r="1"/></>,grid:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,shield:<><path d="M12 3 4 6v5c0 5 3.5 8 8 10 4.5-2 8-5 8-10V6l-8-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,arrow:<path d="m9 18 6-6-6-6"/>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>}
function Card({item,isFeatured=false}:{item:Listing,isFeatured?:boolean}){return <article className="listing-card"><div className="listing-photo" style={{backgroundPosition:(item.photo*14.285)+"% center"}}>{isFeatured&&<b className="featured-badge">★ FEATURED</b>}<span className="verified"><Icon name="shield" size={14}/> VERIFIED</span></div><div className="listing-info"><h3>{item.name}</h3><p>{item.area}, Delhi</p><div className="tags">{item.tags.map(t=><i key={t}>{t}</i>)}</div><div className="rating"><span>★ {item.rating}</span><b>● OPEN NOW</b></div></div></article>}
export default function CityPage(){const params=useParams<{city:string}>(),city=decodeURIComponent(params.city||"delhi").replace(/-/g," "),title=city.replace(/\b\w/g,c=>c.toUpperCase());const[query,setQuery]=useState(""),[area,setArea]=useState("All Areas"),[category,setCategory]=useState("All Categories"),[applied,setApplied]=useState("");const visible=useMemo(()=>listings.filter(x=>(area==="All Areas"||x.area===area)&&x.name.toLowerCase().includes(applied.toLowerCase())&&(category==="All Categories"||x.tags.includes(category))),[area,category,applied]);const submit=(e:FormEvent)=>{e.preventDefault();setApplied(query)};return <div className="city-page">
<header><Link className="brand" href="/"><span>◇</span>CITYSCAPE</Link><nav><Link href="/">HOME</Link><Link href="/locations">LOCATIONS</Link><Link href="/categories">CATEGORIES</Link><a href="#featured">FEATURED</a><a href="#safety">SAFETY</a></nav><div><button className="login">LOGIN</button><a className="primary" href="#post">POST FREE AD</a></div></header>
<main><section className="city-hero"><div className="hero-photo"/><div className="hero-inner"><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/locations">Locations</Link><span>/</span><b>{title}</b></div><h1>EXPLORE <em>{title}</em></h1><p>Discover trusted local services across the city.</p><div className="stats"><div>▤ <span><b>1,240</b><small>ACTIVE LISTINGS</small></span></div><div><Icon name="pin" size={31}/><span><b>42</b><small>POPULAR AREAS</small></span></div></div></div></section>
<form className="city-search" onSubmit={submit}><div><Icon name="search" size={25}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={"Search services in "+title}/></div><select value={area} onChange={e=>setArea(e.target.value)}><option>All Areas</option>{areas.map(a=><option key={a}>{a}</option>)}</select><button>SEARCH</button><section>{areas.map(a=><button type="button" key={a} onClick={()=>setArea(a)}><Icon name="pin" size={15}/>{a}</button>)}</section></form>
<div className="city-content"><section id="featured"><div className="section-head"><h2>FEATURED IN <em>{title}</em></h2><a href="#listings">VIEW ALL <Icon name="arrow"/></a></div><div className="featured-list">{featured.map(x=><Card key={x.name} item={x} isFeatured/>)}</div></section>
<div className="results-layout" id="listings"><aside><h2>FILTERS</h2><label>AREA<select value={area} onChange={e=>setArea(e.target.value)}><option>All Areas</option>{areas.map(a=><option key={a}>{a}</option>)}</select></label><label>CATEGORY<select value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option>{["Food & Drink","Flowers","Health","Spa","Home","Office"].map(a=><option key={a}>{a}</option>)}</select></label><label>PRICE RANGE<select><option>Any Price</option><option>₹0–₹5,000</option><option>₹5,000+</option></select><input type="range"/></label><label>AVAILABILITY<select><option>Anytime</option><option>Open Now</option></select></label><div className="toggle">VERIFIED ONLY <i/></div><button className="apply" onClick={()=>setApplied(query)}>APPLY FILTERS</button></aside>
<section className="all-listings"><div className="results-head"><div><h2>ALL LISTINGS IN <em>{title}</em></h2><p>{visible.length?"1,24"+visible.length+" results found":"No results found"}</p></div><div className="view"><button><Icon name="grid"/></button><button><Icon name="list"/></button><select><option>MOST POPULAR</option><option>TOP RATED</option></select></div></div><div className="listing-grid">{visible.map(x=><Card key={x.name} item={x}/>)}</div></section></div>
<section><div className="section-head"><h2>POPULAR AREAS IN <em>{title}</em></h2><a href="#">VIEW ALL <Icon name="arrow"/></a></div><div className="area-grid">{areaCards.map((x,i)=><button key={x[0]} onClick={()=>setArea(x[0])}><div style={{backgroundPosition:(i*20)+"% center"}}/><b>{x[0]}</b><span>{x[1]} LISTINGS</span></button>)}</div></section>
<section><div className="section-head"><h2>NEARBY CITIES</h2></div><div className="nearby-grid">{nearby.map((x,i)=><Link href={"/locations/"+x[0].toLowerCase()} key={x[0]}><div style={{backgroundPosition:(i*25)+"% center"}}/><b>{x[0]}</b><span>{x[1]} LISTINGS</span></Link>)}</div></section>
<section className="safety" id="safety"><Icon name="shield" size={75}/><div><h2>CONNECT SAFELY AND CONFIDENTLY</h2><p>Your safety matters to us. Follow our tips and stay informed while connecting with services across the city.</p></div><button>READ SAFETY TIPS <Icon name="arrow"/></button></section></div></main>
<footer><div><Link className="brand" href="/"><span>◇</span>CITYSCAPE</Link><p>Discover trusted local services across India’s cities. Verified listings, real reviews, and a safer way to connect.</p></div>{[["EXPLORE","Locations","Categories","Featured","New Listings"],["SUPPORT","Help Center","Safety Tips","Contact Us","Report an Issue"],["LEGAL","Terms of Use","Privacy Policy","Cookie Policy","Disclaimer"],["POPULAR CITIES","Delhi","Mumbai","Bangalore","Hyderabad"]].map(g=><div key={g[0]}><h3>{g[0]}</h3>{g.slice(1).map(x=><a href="#" key={x}>{x}</a>)}</div>)}<div><h3>STAY UPDATED</h3><p>Subscribe to get the latest listings and updates in your city.</p><input placeholder="Enter your email"/><button>SUBSCRIBE</button></div></footer></div>}
