"use client";
import {FormEvent,useMemo,useState} from "react";
import Link from "next/link";
import "./locations.css";
type City={name:string;count:number;state:string};
const featured=[["Delhi",18743],["Mumbai",24196],["Bengaluru",16283],["Hyderabad",12974],["Chennai",11458],["Kolkata",10689]];
const raw=[["Ahmedabad",9234,"Gujarat"],["Agra",2105,"Uttar Pradesh"],["Ajmer",1204,"Rajasthan"],["Allahabad",2876,"Uttar Pradesh"],["Amritsar",2345,"Punjab"],["Bengaluru",16283,"Karnataka"],["Bhopal",2789,"Madhya Pradesh"],["Bhubaneswar",2101,"Odisha"],["Bareilly",1876,"Uttar Pradesh"],["Patna",5432,"Bihar"],["Chennai",11458,"Tamil Nadu"],["Coimbatore",2345,"Tamil Nadu"],["Cochin",2123,"Kerala"],["Chandigarh",2876,"Punjab"],["Cuttack",1234,"Odisha"],["Delhi",18743,"Delhi"],["Dehradun",1765,"Uttarakhand"],["Dhanbad",1234,"Jharkhand"],["Durgapur",1156,"West Bengal"],["Dewas",876,"Madhya Pradesh"],["Hyderabad",12974,"Telangana"],["Hubli",1245,"Karnataka"],["Hisar",876,"Haryana"],["Haldwani",654,"Uttarakhand"],["Haridwar",1034,"Uttarakhand"],["Kolkata",10689,"West Bengal"],["Kochi",2123,"Kerala"],["Kanpur",2345,"Uttar Pradesh"],["Kozhikode",1234,"Kerala"],["Kota",1456,"Rajasthan"],["Mumbai",24196,"Maharashtra"],["Mysuru",1876,"Karnataka"],["Madurai",1234,"Tamil Nadu"],["Mangalore",1567,"Karnataka"],["Meerut",1345,"Uttar Pradesh"],["Pune",8765,"Maharashtra"],["Prayagraj",1987,"Uttar Pradesh"],["Panchkula",876,"Haryana"],["Jalandhar",1234,"Punjab"],["Puducherry",654,"Others"],["Vadodara",2345,"Gujarat"],["Varanasi",2876,"Uttar Pradesh"],["Vijayawada",1234,"Andhra Pradesh"],["Visakhapatnam",1456,"Andhra Pradesh"],["Vellore",987,"Tamil Nadu"]];
const cities:City[]=raw.map(x=>({name:x[0] as string,count:x[1] as number,state:x[2] as string}));
const states=["All States","Andhra Pradesh","Bihar","Gujarat","Haryana","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Odisha","Punjab","Rajasthan","Tamil Nadu","Telangana","Uttar Pradesh","West Bengal","Others"],fmt=new Intl.NumberFormat("en-IN");
function Icon({name,size=20}:{name:string,size?:number}){const p:Record<string,React.ReactNode>={home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10"/></>,pin:<><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,grid:<><rect x="3" y="3" width="6" height="6"/><rect x="15" y="3" width="6" height="6"/><rect x="3" y="15" width="6" height="6"/><rect x="15" y="15" width="6" height="6"/></>,star:<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z"/>,search:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,plus:<><circle cx="12" cy="12" r="8"/><path d="M12 8v8M8 12h8"/></>,arrow:<><path d="M5 12h14M14 7l5 5-5 5"/></>,reset:<><path d="M4 12a8 8 0 1 0 2.3-5.7L4 8"/><path d="M4 3v5h5"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>}
export default function LocationsClientPage(){const[state,setState]=useState("All States"),[query,setQuery]=useState(""),[search,setSearch]=useState("");const visible=useMemo(()=>cities.filter(c=>(state==="All States"||c.state===state)&&c.name.toLowerCase().includes(search.toLowerCase())),[state,search]);const groups=useMemo(()=>Object.entries(visible.reduce<Record<string,City[]>>((a,c)=>{(a[c.name[0]]||=[]).push(c);return a},{})).sort(),[visible]);const submit=(e:FormEvent)=>{e.preventDefault();setSearch(query.trim())};return <div className="locations-page">
<div className="offer"><span>🎁 <b>Limited Time Offer:</b> Post your ad for FREE and get more visibility!</span><a href="#post">Learn More</a></div>
<header className="site-header"><Link className="logo" href="/"><span>●▲</span><b>mycityqueen</b></Link><nav><Link href="/"><Icon name="home"/>Home</Link><Link className="active" href="/locations"><Icon name="pin"/>Locations</Link><Link href="/categories"><Icon name="grid"/>Categories</Link><a href="#popular"><Icon name="star"/>Featured</a></nav><a className="post-btn" href="#post"><Icon name="plus" size={18}/>Post Free Ad</a></header>
<main><section className="hero"><div className="crumb"><Link href="/">Home</Link><span>/</span><b>Locations</b></div><div className="hero-copy"><p>EXPLORE BY LOCATION</p><h1>Find Listings Near You</h1><span>Discover verified listings across cities and states.<br/>Search your area or explore popular locations.</span><form onSubmit={submit}><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search city or state"/><button>Search</button></form></div><div className="hero-pin"><Icon name="pin" size={54}/></div><div className="hero-globe"/></section>
<div className="content"><section id="popular"><h2>Popular Cities</h2><div className="featured-grid">{featured.map((c,i)=><Link key={c[0]} className="featured-card" href={"/locations/"+String(c[0]).toLowerCase()}><div className="city-photo" style={{backgroundPosition:(i*20)+"% center"}}/><div className="city-meta"><h3>{c[0]}</h3><span>{fmt.format(c[1] as number)} Listings</span></div><i><Icon name="arrow" size={16}/></i></Link>)}</div></section>
<div className="directory-layout" id="browse"><aside><h2>Filter by State</h2><div className="state-list">{states.map(s=><button key={s} className={state===s?"selected":""} onClick={()=>setState(s)}>{s==="All States"&&<Icon name="pin" size={15}/>}<span>{s}</span>{s!=="All States"&&<small>{cities.filter(c=>c.state===s).length*7+31}</small>}</button>)}</div><button className="reset" onClick={()=>{setState("All States");setSearch("");setQuery("")}}><Icon name="reset" size={17}/>Reset Filters</button></aside><section className="browse"><div className="browse-head"><h2>Browse All Locations</h2><span># Cities</span></div>{groups.length?groups.map(([letter,list])=><div className="letter-row" key={letter}><div className="letter-head"><b>{letter}</b><a href="#popular">View all {Math.max(list.length,8)} cities <Icon name="arrow" size={14}/></a></div><div className="city-list">{list.slice(0,5).map(c=><a href="#post" key={c.name}><b>{c.name}</b><span>{fmt.format(c.count)}</span></a>)}</div></div>):<div className="empty">No matching locations found.</div>}</section></div>
<section className="cta" id="post"><div className="ad-art">⌸ <i>+</i></div><div><h2>Don’t see your city?</h2><p>Post your ad now and reach people everywhere.</p><a className="post-btn" href="#"><Icon name="plus" size={18}/>Post Your Free Ad</a></div><div className="world">••• ·•· •••<br/>· ••• ·• •<br/>•• · ••••</div></section></div></main>
<footer><div className="footer-grid"><div><Link className="logo" href="/"><span>●▲</span><b>mycityqueen</b></Link><p>MyCityQueen is your trusted platform to discover and post verified listings across India.</p></div><Footer title="QUICK LINKS" links={["Home","Locations","Categories","Featured","How It Works"]}/><Footer title="POPULAR CATEGORIES" links={["Escorts","Massage","Dating","Jobs","Real Estate"]}/><Footer title="HELP & SUPPORT" links={["Help Center","Safety Tips","Terms of Use","Privacy Policy"]}/><div><h3>NEWSLETTER</h3><p>Subscribe to get updates and exclusive offers.</p><input placeholder="Enter your email"/><button className="subscribe">Subscribe</button></div></div><div className="copyright"><span>© 2026 MyCityQueen. All rights reserved.</span><span>Made with <b>♥</b> in India</span></div></footer></div>}
function Footer({title,links}:{title:string;links:string[]}){return <div><h3>{title}</h3>{links.map(x=><a className="footer-link" href="#" key={x}>{x}</a>)}</div>}
