"use client";
import Link from "next/link";
import {FormEvent,useMemo,useState} from "react";
import "./search.css";
type Result={name:string;area:string;category:string;rating:number,reviews:number,availability:string,photo:number,description:string,verified:boolean};
const data:Result[]=[
 {name:"Pankaj Car Care",area:"Lajpat Nagar",category:"Automotive",rating:4.8,reviews:124,availability:"Available Now",photo:0,description:"Complete car cleaning, detailing & premium wash services.",verified:true},
 {name:"Aditi Home Tuition",area:"Dwarka",category:"Tutors & Coaching",rating:4.9,reviews:98,availability:"Available Now",photo:1,description:"Personalized home tuition for Classes 1–12 across all subjects.",verified:true},
 {name:"Rohan Photography",area:"Connaught Place",category:"Photography",rating:4.7,reviews:73,availability:"Available Today",photo:2,description:"Professional photography for events, portraits & more.",verified:false},
 {name:"Shine Home Cleaning",area:"Mayur Vihar",category:"Home Services",rating:4.6,reviews:156,availability:"Available Now",photo:3,description:"Residential & commercial cleaning with trusted professionals.",verified:true},
 {name:"Neha Yoga Studio",area:"GK II",category:"Health & Wellness",rating:4.8,reviews:112,availability:"Available Now",photo:4,description:"Yoga & wellness sessions for a healthier and balanced life.",verified:false},
 {name:"Career Path Coaching",area:"Pitampura",category:"Tutors & Coaching",rating:4.7,reviews:89,availability:"Available This Week",photo:5,description:"Exam preparation for UPSC, SSC, Banking & more.",verified:true},
 {name:"QuickFix Electricals",area:"Rohini",category:"Home Services",rating:4.6,reviews:134,availability:"Available Now",photo:6,description:"Electrical repairs, installations & home wiring solutions.",verified:true},
 {name:"Tasty Bites Catering",area:"Saket",category:"Events",rating:4.8,reviews:101,availability:"Available Today",photo:7,description:"Delicious catering for parties, events & special occasions.",verified:false},
 {name:"LegalEase Associates",area:"Karol Bagh",category:"Legal Services",rating:4.9,reviews:67,availability:"Available Now",photo:8,description:"Legal consultation for civil, family, property & related matters.",verified:true},
];
const categories=["All Categories","Automotive","Tutors & Coaching","Photography","Home Services","Health & Wellness","Events","Legal Services"];
function Icon({name,size=20}:{name:string,size?:number}){const p:Record<string,React.ReactNode>={search:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,pin:<><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,grid:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,list:<><path d="M9 6h11M9 12h11M9 18h11"/><circle cx="4" cy="6" r="1"/><circle cx="4" cy="12" r="1"/><circle cx="4" cy="18" r="1"/></>,sliders:<><path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2"/><circle cx="15" cy="12" r="2"/><circle cx="8" cy="18" r="2"/></>,shield:<><path d="M12 3 4 6v5c0 5 3.5 8 8 10 4.5-2 8-5 8-10V6l-8-3Z"/><path d="m9 12 2 2 4-5"/></>,heart:<path d="M12 21S3 16 3 9a5 5 0 0 1 9-3 5 5 0 0 1 9 3c0 7-9 12-9 12Z"/>,users:<><circle cx="8" cy="8" r="3"/><circle cx="17" cy="8" r="3"/><path d="M2 20c0-5 2-7 6-7s6 2 6 7M13 14c1-.7 2.3-1 4-1 4 0 5 2 5 7"/></>,chat:<><path d="M4 4h16v12H8l-4 4V4Z"/><path d="M8 9h.01M12 9h.01M16 9h.01"/></>,flag:<path d="M5 21V4h12l2 4-2 4H5"/>,arrow:<path d="m9 18 6-6-6-6"/>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>}
function ResultCard({r}:{r:Result}){return <article className="result-card"><div className="result-photo" style={{backgroundPosition:(r.photo*12.5)+"% center"}}>{r.verified&&<b><Icon name="shield" size={16}/> Verified</b>}<button aria-label="Save"><Icon name="heart"/></button></div><div className="result-info"><h3>{r.name}</h3><small><Icon name="pin" size={14}/>{r.area}, Delhi</small><p>{r.description}</p><div className="result-meta"><span>{r.rating} ⭐ <small>({r.reviews})</small></span><b className={r.availability.includes("Today")||r.availability.includes("Week")?"today":""}>{r.availability}</b></div><Link href={"/profile/"+r.name.toLowerCase().replaceAll(" ","-")}>View Profile</Link></div></article>}
export default function SearchPage(){const[query,setQuery]=useState(""),[search,setSearch]=useState(""),[location,setLocation]=useState("Delhi"),[category,setCategory]=useState("All Categories"),[verified,setVerified]=useState(true),[available,setAvailable]=useState(true),[minRating,setMinRating]=useState(0),[maxPrice,setMaxPrice]=useState(5000),[sort,setSort]=useState("Newest first"),[grid,setGrid]=useState(true);const visible=useMemo(()=>data.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())&&(category==="All Categories"||x.category===category)&&(!verified||x.verified)&&(!available||x.availability.includes("Available"))&&x.rating>=minRating).sort((a,b)=>sort==="Highest rated"?b.rating-a.rating:0),[search,category,verified,available,minRating,sort]);const submit=(e:FormEvent)=>{e.preventDefault();setSearch(query.trim())};const clear=()=>{setQuery("");setSearch("");setLocation("Delhi");setCategory("All Categories");setVerified(false);setAvailable(false);setMinRating(0);setMaxPrice(5000)};return <div className="search-page">
 <div className="search-safety"><span><Icon name="shield" size={16}/> Stay safe, trade smart. Meet in public places and verify before you pay.</span><a href="#safety">Learn more　→</a></div><header><Link className="search-logo" href="/">MYCITYQUEEN</Link><nav><Link href="/">Home</Link><Link href="/locations">Locations⌄</Link><Link href="/categories">Categories⌄</Link><a href="#safety">Safety</a></nav><div>♡　◉　<a href="#post">Post Free Ad</a></div></header>
 <main><div className="search-wrap"><div className="search-crumb"><Link href="/">Home</Link><span>/</span><b>Search Results</b></div><section className="search-box"><h1>Search Results</h1><form onSubmit={submit}><div><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What are you looking for?"/></div><label><Icon name="pin"/><select value={location} onChange={e=>setLocation(e.target.value)}><option>Delhi</option><option>Mumbai</option><option>Bengaluru</option><option>Chennai</option></select></label><label><Icon name="grid"/><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><button><Icon name="search"/>Search</button></form></section>
 <section className="results-bar"><b>♨　128 results found</b><div><span>{location}　×</span><span>{category}　×</span>{verified&&<span>Verified Only　×</span>}<button onClick={clear}>Clear all</button></div><select value={sort} onChange={e=>setSort(e.target.value)}><option>Newest first</option><option>Highest rated</option></select><button className={grid?"active":""} onClick={()=>setGrid(true)}><Icon name="grid"/></button><button className={!grid?"active":""} onClick={()=>setGrid(false)}><Icon name="list"/></button></section>
 <div className="search-layout"><aside><h2><Icon name="sliders"/>Filters</h2><label><span><Icon name="pin"/>Location</span><select value={location} onChange={e=>setLocation(e.target.value)}><option>Delhi</option><option>Mumbai</option><option>Bengaluru</option></select></label><label><span><Icon name="grid"/>Category</span><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label><span>▤　Service Type</span><select><option>All Service Types</option><option>At Home</option><option>On Site</option></select></label><div className="filter-toggle"><span><Icon name="shield"/>Verified Only<small>Show verified listings only</small></span><button className={verified?"on":""} onClick={()=>setVerified(!verified)}><i/></button></div><fieldset><legend>▦　Availability</legend><label><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/>Available Now</label><label><input type="checkbox"/>Available Today</label><label><input type="checkbox"/>Available This Week</label><label><input type="checkbox"/>Choose Dates</label></fieldset><label><span>₹　Price Range</span><div className="price-inputs"><i>₹ Min</i><i>₹ {maxPrice}</i></div><input type="range" min="500" max="10000" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/></label><fieldset className="ratings"><legend>☆　Rating</legend>{[5,4,3,2,1].map(n=><label key={n}><input type="radio" name="rating" checked={minRating===n} onChange={()=>setMinRating(n)}/><span>{"★".repeat(n)}{"☆".repeat(5-n)}</span>{n<5&&" & up"}</label>)}</fieldset><button className="apply-search" onClick={()=>setSearch(query)}>Apply Filters</button><button className="clear-search" onClick={clear}>Clear All</button></aside>
 <section className={grid?"results-grid":"results-grid list-view"}>{visible.map(r=><ResultCard r={r} key={r.name}/>)}</section></div>
 <section className="related-searches"><h2><Icon name="search"/>Related searches</h2><div>{["Home Cleaning Services in Delhi","Car Wash Near Me","Home Tutors in Delhi","Event Photographers Delhi","Yoga Classes Near Me","Catering Services in Delhi"].map(x=><button key={x} onClick={()=>{setQuery(x);setSearch(x)}}>{x}</button>)}</div></section><div className="search-pagination"><button>‹</button>{[1,2,3,4,5].map(n=><button className={n===1?"active":""} key={n}>{n}</button>)}<span>…　13</span><button>›</button></div>
 <section className="search-safe" id="safety"><div><Icon name="shield" size={70}/><span><h2>Your safety is our priority</h2><p>We encourage safe interactions for everyone. Meet in public places,<br/>verify the listing, and never pay in advance.</p><a href="#">Learn more　→</a></span></div>{[[Icon,"users","Meet in public places"],[Icon,"shield","Verify before you pay"],[Icon,"chat","Communicate within platform"],[Icon,"flag","Report suspicious activity"]].map((x,i)=>{const I=x[0] as typeof Icon;return <div key={i}><I name={x[1] as string} size={34}/><span>{x[2] as string}</span></div>})}</section><section className="search-cta" id="post"><div><h2>Post Your Free Ad Today</h2><p>Reach thousands of people in your local area.</p><a href="#">Post Free Ad　　→</a></div><div className="ad-outline">▤<b>＋</b></div></section></div></main>
 <footer><div><Link className="search-logo" href="/">MYCITYQUEEN</Link><p>Your trusted local marketplace to discover and connect with services around you.</p><span>●　◎　♥　▶</span></div>{[["⌖ Locations","Delhi","Mumbai","Bengaluru","Chennai","Kolkata","View all cities ›"],["▦ Categories","Home Services","Tutors & Coaching","Events","Automotive","Health & Wellness","View all categories ›"],["? Help","Help Center","Safety Tips","How It Works","Contact Us","Report an Issue"],["♢ Legal","Terms of Use","Privacy Policy","Cookie Policy","Disclaimer"]].map(g=><div key={g[0]}><h3>{g[0]}</h3>{g.slice(1).map(x=><a href="#" key={x}>{x}</a>)}</div>)}<div><h3>✉ Newsletter</h3><p>Subscribe to get updates and useful tips.</p><input placeholder="Enter your email"/><button>Subscribe</button></div></footer>
 </div>}
